# Place any default configuration for solr_wrapper here
# port: 8983
port: 8983
verbose: true
version: '8.0.0'
instance_dir: 'withMarc'
download_dir: 'projects'
collection:
  dir: solr/conf/
  name: cogniva-core